### ISSUE TITLE
minimum iOS version

### ISSUE THREAD

**Issue by EralpB** [fouquet/RFAboutView#1]
Why did you chose iOS8 as minimum requirement? Can I make this library work in iOS7?

**Comment by fouquet** [comment]
Mostly because of the UIVisualEffectsView. It's not available on iOS 7, which means checks for system version and writing a replacement that renders the effect the same way. Given iOS 8 is 80+% of the market, I didn't see the point.

But I'm not stopping you ;-)

Other than the UIVisualEffectsView, there should be nothing that wouldn't work with iOS 7.

**Comment by EralpB** [comment]
Thank you for your swift support ;)
